name: Static Analysis

on:
  push:
  pull_request:
    branches: [master]

jobs:
  luacheck:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install LuaJIT
        run: sudo apt-get install luajit

      # LuaRocks needs the 5.1 headers to compile LuaCheck later
      - name: Install LuaJIT development package
        run: sudo apt-get install libluajit-5.1-dev

      - name: Download LuaRocks
        run: wget https://luarocks.org/releases/luarocks-3.7.0.tar.gz

      - name: Unpack luarocks release
        run: tar zxpf luarocks-3.7.0.tar.gz

      - name: Install Luarocks
        run: cd luarocks-3.7.0 && ./configure && make && sudo make install

      - name: Install luacheck
        run: sudo luarocks install luacheck

      - name: Perform static analysis
        run: cd .. && luacheck .
