name: Static Analysis

on:
  push:

jobs:
  luacheck:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Run luacheck via GitHub Super-Linter
        run: github/super-linter@v4.2.2